Tasks_03:
DmytriiTsiupko/rd-homeworks pull request #4
Opened 2022-12-14 14:57 UTC by DmytriiTsiupko

1. Create a program that will expect the user to enter text and output information for each typed character:

- this "number" + what it is (even, odd),
- this is a "letter" + what is it (uppercase or lowercase),
- is a "symbol"

2. Create a program that will print “I love Python” to the console every 4.2 seconds until its execution is manually interrupted.

2022-12-15 18:27 UTC, klymenok requested changes
Solution is good, but I would like to ask you make some changes to make it looks better

2022-12-15 18:27 UTC, klymenok commented on Lesson_03/solution_task_n1.py
> +        elif char.isalpha() == True:
You can skip `== True` since if will make this check in the end. So it can be simplified to `elif char.isalpha():`

2022-12-15 18:27 UTC, klymenok commented on Lesson_03/solution_task_n1.py
> +            if char.isdigit() != True and char.isalpha() != True:
This `if` statement is not needed since we can assume that everything that is not a digit and is not a letter is a symbol.

2022-12-15 18:27 UTC, klymenok commented on Lesson_03/solution_task_n2.py
> +    time_out = time.sleep(4.2)
You can use it simply `time.sleep(4.2)`. There is no need to save the result in `time_out` variable

2022-12-15 19:29 UTC, DmytriiTsiupko commented
In solution_task_n2.py:
-Deleted variable for time.sleep(4.2)

2022-12-17 16:17 UTC, klymenok approved these changes
Looks good!

2022-12-17 16:25 UTC, merged